openai:
  model: davinci-002
  secret-key: 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

server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gpt?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      username: root
      password: phj@3473

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create
